import Head from 'next/head'
import Link from 'next/link'
import classes from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={classes.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={classes.main}>
        bingo!
        <button>
          <Link href='/profile/23'>search</Link>
        </button>
      </main>
    </div>
  )
}
