import Head from 'next/head';
import SearchUsername from "../Components/SearchUsername";
import classes from '../styles/Home.module.css';

export default function Home() {
  return (
    <div className={classes.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={classes.main}>
          <SearchUsername/>
      </main>
    </div>
  )
}
